import tiktoken
import json
from typing import Dict, Any

class TOKEN_validator():

    def __init__(self, model_name: str = "gpt-3.5-turbo"):
        self.encoding = tiktoken.encoding_for_model(model_name)
        self.model_name = model_name
    
    def validate(self, original_json: Any, toon_output: str) -> Dict[str, Any]:
        
        # Converting JSON to str
        original_str = json.dumps(original_json, separators=(',', ':'))
        
        #tokencount
        original_tokens = self._count_tokens(original_str)
        toon_tokens = self._count_tokens(toon_output)
        
        # Calculate savings
        savings_tokens = original_tokens - toon_tokens
        savings_percentage = (savings_tokens / original_tokens * 100) if original_tokens > 0 else 0
        
        return {
            "original_tokens": original_tokens,
            "toon_tokens": toon_tokens,
            "savings_tokens": savings_tokens,
            "savings_percentage": round(savings_percentage, 2)
        }
    
    def _count_tokens(self, text: str) -> int:
        
        tokens = self.encoding.encode(text)
        return len(tokens)
    
    def validate_with_details(self, original_json: Any, toon_output: str) -> Dict[str, Any]:
        
        basic_stats = self.validate(original_json, toon_output)
        
        original_str = json.dumps(original_json, separators=(',', ':'))
        
        #  metrics
        original_chars = len(original_str)
        toon_chars = len(toon_output)
        char_savings = original_chars - toon_chars
        char_savings_pct = (char_savings / original_chars * 100) if original_chars > 0 else 0
        
        # tokens per character
        original_efficiency = basic_stats["original_tokens"] / original_chars if original_chars > 0 else 0
        toon_efficiency = basic_stats["toon_tokens"] / toon_chars if toon_chars > 0 else 0
        
        return {
            **basic_stats,
            "character_stats": {
                "original_chars": original_chars,
                "toon_chars": toon_chars,
                "char_savings": char_savings,
                "char_savings_percentage": round(char_savings_pct, 2)
            },
            "efficiency": {
                "original_tokens_per_char": round(original_efficiency, 3),
                "toon_tokens_per_char": round(toon_efficiency, 3),
                "efficiency_improvement": round((toon_efficiency - original_efficiency) / original_efficiency * 100, 2) if original_efficiency > 0 else 0
            },
            "model": self.model_name
        }
    
    def compare_formats(self, original_json: Any, toon_output: str) -> str:
        stats = self.validate_with_details(original_json, toon_output)
        
        # u can change this coz generated by ai...

        report = f"""
Token Validation Report
{'='*50}
Model: {stats['model']}

Original Format (JSON):
  - Tokens: {stats['original_tokens']:,}
  - Characters: {stats['character_stats']['original_chars']:,}

TOON Format:
  - Tokens: {stats['toon_tokens']:,}
  - Characters: {stats['character_stats']['toon_chars']:,}

Savings:
  - Token Reduction: {stats['savings_tokens']:,} ({stats['savings_percentage']}%)
  - Character Reduction: {stats['character_stats']['char_savings']:,} ({stats['character_stats']['char_savings_percentage']}%)

Efficiency:
  - Original: {stats['efficiency']['original_tokens_per_char']} tokens/char
  - TOON: {stats['efficiency']['toon_tokens_per_char']} tokens/char
  - Improvement: {stats['efficiency']['efficiency_improvement']}%
{'='*50}
        """
        
        return report.strip()